version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "CassandraCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "Rack1"
      CASSANDRA_SEEDS: "cassandra"
    ports:
      - "9042:9042"

volumes:
  cassandra_data:

# networks:
#   cassandra_network:
#     driver: bridge